### ISSUE TITLE
question about settings

### ISSUE THREAD

**Issue by sander816** [mkpascal/mk_liquidsoap_processing#6]
do you use these settings also for your c9 radio station?
I am looking to get the same sound as on your online radio

**Comment by mkpascal** [comment]
Sorry, C9 Radio doesn't use these settings. We're using something entirely different.

If you're trying to get a similar sound, you should try something more advanced like Breakaway One or StereoTool.

**Comment by sander816** [comment]
thanx, but on a remote debian host i cannot use external compressors or breakaway software

**Comment by sander816** [comment]
i am somehow familiar with limiters / compressers etc. 
Can you point me in a direction to get a little closer to the sound of these france hit stations, and/or C9?

I love that sound processing

**Comment by mkpascal** [comment]
You can use StereoTool on a remote Linux host. It has a lot of presets you can test on a regular computer then you can import them into the Linux version of StereoTool that can be integrated into Liquidsoap or another software.

With that said, I'll lock this conversation because this isn't related to this repository. I'll suggest you to continue the conversation in the StereoTool forum: https://forums.stereotool.com/.

Thanks for understanding.
